#!/bin/python3

import math
import os
import random
import re
import sys


def hourglassSum(arr):
    max_sum = None

    num_of_cols = len(arr)
    num_of_rows = len(arr[0])

    for j in range(num_of_cols):
        for i in range(num_of_rows):
            if i+2 < num_of_rows and j+2< num_of_cols:
                h_sum = arr[i][j]+arr[i][j+1]+arr[i][j+2]\
                                 +arr[i+1][j+1]\
                        +arr[i+2][j]+arr[i+2][j+1]+arr[i+2][j+2]

                if max_sum == None or max_sum < h_sum:
                    max_sum = h_sum

    return max_sum    




if __name__ == '__main__':
    fptr = open(os.environ['OUTPUT_PATH'], 'w')

    arr = []

    for _ in range(6):
        arr.append(list(map(int, input().rstrip().split())))

    result = hourglassSum(arr)

    fptr.write(str(result) + '\n')

    fptr.close()
